### ISSUE TITLE
Cannot find module 'big.js' or its corresponding type declarations

### ISSUE THREAD

**Issue by okovpashko** [xxczaki/cashify#19]
After upgrading cashify to v3 I start getting the following build error in my TypeScript project:
```
node_modules/cashify/dist/lib/options.d.ts:1:37 - error TS2307: Cannot find module 'big.js' or its corresponding type declarations.

1 import type { BigSource, Big } from 'big.js';
```

Seems like it's because `big.js` is placed into the `devDependencies` section and those dependencies are not installed when the library is installed to another project.

Can we move `big.js` and `@types/big.js` to the `dependencies` section?

**Comment by xxczaki** [comment]
Thanks for catching that! I just release 3.0.1 with a fix :smile:

**Comment by okovpashko** [comment]
Wow! Thank you for such a quick reaction!
